Repository RAF-SI-2021/Banka-Back, pull requests merged in 2022-04, with the labels that each got.

#44 Korisnicki servis
  README.md
  pom.xml
  src/main/java/si/banka/korisnicki_servis/config/DatabaseConfig.java
  src/main/java/si/banka/korisnicki_servis/controller/UserController.java
  src/main/java/si/banka/korisnicki_servis/repository/RoleRepository.java
  src/main/java/si/banka/korisnicki_servis/service/implementation/UserServiceImplementation.java
  src/main/resources/application.properties
Labels: area/backend

#54 InfluxDB Scraping
  InfluxScrapper/.gitignore
  InfluxScrapper/Dockerfile
  InfluxScrapper/InfluxScrapper.Tests/FuturesUnitTests.cs
  InfluxScrapper/InfluxScrapper.Tests/InfluxScrapper.Tests.csproj
  InfluxScrapper/InfluxScrapper.sln
  InfluxScrapper/InfluxScrapper/.dockerignore
  InfluxScrapper/InfluxScrapper/Controllers/AlphaVantageForexScrapperController.cs
  InfluxScrapper/InfluxScrapper/Controllers/AlphaVantageStockScrapperController.cs
  InfluxScrapper/InfluxScrapper/Controllers/NasdaqFuturesScrapperController.cs
  InfluxScrapper/InfluxScrapper/InfluxScrapper.csproj
  InfluxScrapper/InfluxScrapper/Models/Constants.cs
  InfluxScrapper/InfluxScrapper/Models/Forex/ForexCacheQuery.cs
  InfluxScrapper/InfluxScrapper/Models/Forex/ForexQuery.cs
  InfluxScrapper/InfluxScrapper/Models/Forex/ForexResult.cs
  InfluxScrapper/InfluxScrapper/Models/Forex/ForexType.cs
  InfluxScrapper/InfluxScrapper/Models/Future/FutureCacheQuery.cs
  InfluxScrapper/InfluxScrapper/Models/Future/FutureDataResult.cs
  InfluxScrapper/InfluxScrapper/Models/Future/FutureQuery.cs
  InfluxScrapper/InfluxScrapper/Models/Future/FutureResult.cs
  InfluxScrapper/InfluxScrapper/Models/Stock/StockCacheQuery.cs
  InfluxScrapper/InfluxScrapper/Models/Stock/StockQuery.cs
  InfluxScrapper/InfluxScrapper/Models/Stock/StockResult.cs
  InfluxScrapper/InfluxScrapper/Models/Stock/StockScrapeQuery.cs
  InfluxScrapper/InfluxScrapper/Models/Stock/StockType.cs
  InfluxScrapper/InfluxScrapper/Models/Stock/StockUpdateQuery.cs
  InfluxScrapper/InfluxScrapper/Program.cs
  InfluxScrapper/InfluxScrapper/Properties/launchSettings.json
  InfluxScrapper/InfluxScrapper/WeatherForecast.cs
  InfluxScrapper/InfluxScrapper/appsettings.Development.json
  InfluxScrapper/InfluxScrapper/appsettings.json
  InfluxScrapper/InfluxScrapper/storage/futuredata.json
Labels: area/backend

#91 Add Stock quotes and Forex exhange rates to scrapper
  InfluxScrapper/InfluxScrapper/Controllers/AlphaVantageForexScrapperController.cs
  InfluxScrapper/InfluxScrapper/Controllers/AlphaVantageStockScrapperController.cs
  InfluxScrapper/InfluxScrapper/Models/Forex/ForexBody.cs
  InfluxScrapper/InfluxScrapper/Models/Forex/ForexExchangeRateCacheQuery.cs
  InfluxScrapper/InfluxScrapper/Models/Forex/ForexExchangeRateQuery.cs
  InfluxScrapper/InfluxScrapper/Models/Forex/ForexExchangeRateResult.cs
  InfluxScrapper/InfluxScrapper/Models/Forex/ForexExhangeRateJson.cs
  InfluxScrapper/InfluxScrapper/Models/Stock/StockCacheQuery.cs
  InfluxScrapper/InfluxScrapper/Models/Stock/StockQuoteCacheQuery.cs
  InfluxScrapper/InfluxScrapper/Models/Stock/StockQuoteQuery.cs
  InfluxScrapper/InfluxScrapper/Models/Stock/StockQuoteResult.cs
  InfluxScrapper/InfluxScrapper/Utilites/AlphaVantageScrapper.cs
  InfluxScrapper/InfluxScrapper/Utilites/InfluxDBUtilites.cs
  InfluxScrapper/InfluxScrapper/Utilites/RetryUtilities.cs
Labels: enhancement, area/backend

#93 Update otp api
  user-service/src/main/java/rs/edu/raf/banka/user_service/controller/UserController.java
Labels: bug

#96 Bug Fixes and UnitTests Influx Scrapper
  InfluxScrapper/InfluxScrapper.Tests/ForexUnitTests.cs
  InfluxScrapper/InfluxScrapper.Tests/FuturesUnitTests.cs
  InfluxScrapper/InfluxScrapper.Tests/StockUnitTests.cs
  InfluxScrapper/InfluxScrapper/Controllers/AlphaVantageForexScrapperController.cs
  InfluxScrapper/InfluxScrapper/Controllers/AlphaVantageStockScrapperController.cs
  InfluxScrapper/InfluxScrapper/Models/Forex/ForexQuery.cs
  InfluxScrapper/InfluxScrapper/Models/Stock/StockScrapeQuery.cs
Labels: bug

#129 Provera kesa pre upisivanja influx
  InfluxScrapper/InfluxScrapper.Tests/ForexUnitTests.cs
  InfluxScrapper/InfluxScrapper.Tests/FuturesUnitTests.cs
  InfluxScrapper/InfluxScrapper.Tests/StockUnitTests.cs
  InfluxScrapper/InfluxScrapper/Controllers/AlphaVantageForexScrapperController.cs
  InfluxScrapper/InfluxScrapper/Controllers/AlphaVantageStockScrapperController.cs
  InfluxScrapper/InfluxScrapper/Controllers/ForexExchangeInfluxScrapperController.cs
  InfluxScrapper/InfluxScrapper/Controllers/ForexInfluxScrapperController.cs
  InfluxScrapper/InfluxScrapper/Controllers/FutureDataScrapperController.cs
  InfluxScrapper/InfluxScrapper/Controllers/FutureInfluxScrapperController.cs
  InfluxScrapper/InfluxScrapper/Controllers/NasdaqFuturesScrapperController.cs
  InfluxScrapper/InfluxScrapper/Controllers/StockInfluxScrapperController.cs
  InfluxScrapper/InfluxScrapper/Controllers/StockQuoteInfluxScrapperController.cs
  InfluxScrapper/InfluxScrapper/InfluxScrapper.csproj
  InfluxScrapper/InfluxScrapper/Models/Controllers/InfluxScrapperController.cs
  InfluxScrapper/InfluxScrapper/Models/Exchange/ForexExchangeRateCacheQuery.cs
  InfluxScrapper/InfluxScrapper/Models/Exchange/ForexExchangeRateQuery.cs
  InfluxScrapper/InfluxScrapper/Models/Exchange/ForexExchangeRateResult.cs
  InfluxScrapper/InfluxScrapper/Models/Exchange/ForexExhangeRateJson.cs
  InfluxScrapper/InfluxScrapper/Models/Forex/ForexCacheQuery.cs
  InfluxScrapper/InfluxScrapper/Models/Forex/ForexExchangeRateCacheQuery.cs
  InfluxScrapper/InfluxScrapper/Models/Forex/ForexQuery.cs
  InfluxScrapper/InfluxScrapper/Models/Forex/ForexResult.cs
  InfluxScrapper/InfluxScrapper/Models/Future/FutureCacheQuery.cs
  InfluxScrapper/InfluxScrapper/Models/Future/FutureQuery.cs
  InfluxScrapper/InfluxScrapper/Models/Future/FutureResult.cs
  InfluxScrapper/InfluxScrapper/Models/Influx/IInfluxManager.cs
  InfluxScrapper/InfluxScrapper/Models/Influx/IInfluxMeasurementHolder.cs
  InfluxScrapper/InfluxScrapper/Models/Influx/InfluxCacheQuery.cs
  InfluxScrapper/InfluxScrapper/Models/Influx/InfluxManager.cs
  InfluxScrapper/InfluxScrapper/Models/Influx/InvfluxRecord.cs
  InfluxScrapper/InfluxScrapper/Models/Quote/StockQuoteCacheQuery.cs
  InfluxScrapper/InfluxScrapper/Models/Quote/StockQuoteQuery.cs
  InfluxScrapper/InfluxScrapper/Models/Quote/StockQuoteResult.cs
  InfluxScrapper/InfluxScrapper/Models/Stock/StockCacheQuery.cs
  InfluxScrapper/InfluxScrapper/Models/Stock/StockQuery.cs
  InfluxScrapper/InfluxScrapper/Models/Stock/StockQuoteCacheQuery.cs
  InfluxScrapper/InfluxScrapper/Models/Stock/StockResult.cs
  InfluxScrapper/InfluxScrapper/Models/Stock/StockUpdateQuery.cs
  InfluxScrapper/InfluxScrapper/Program.cs
  InfluxScrapper/InfluxScrapper/Utilites/AlphaVantageScrapper.cs
  InfluxScrapper/InfluxScrapper/Utilites/DateTimeUtils.cs
  InfluxScrapper/InfluxScrapper/Utilites/HttpUtilities.cs
  InfluxScrapper/InfluxScrapper/Utilites/InfluxDBUtilites.cs
  InfluxScrapper/InfluxScrapper/Utilites/RetryUtilities.cs
Labels: enhancement

#138 Fix Influx unit tests
  InfluxScrapper/InfluxScrapper.Tests/ForexExhangeRateUnitTests.cs
  InfluxScrapper/InfluxScrapper.Tests/ForexUnitTests.cs
  InfluxScrapper/InfluxScrapper.Tests/FutureDataUnitTests.cs
  InfluxScrapper/InfluxScrapper.Tests/FuturesUnitTests.cs
  InfluxScrapper/InfluxScrapper.Tests/StockQuoteUnitTests.cs
  InfluxScrapper/InfluxScrapper.Tests/StockUnitTests.cs
  InfluxScrapper/InfluxScrapper/Controllers/FutureDataScrapperController.cs
  InfluxScrapper/InfluxScrapper/Models/Forex/ForexResult.cs
Labels: bug

#140 [Fix] Set otp seecret
  user-service/src/main/java/rs/edu/raf/banka/user_service/controller/UserController.java
  user-service/src/main/java/rs/edu/raf/banka/user_service/service/UserService.java
  user-service/src/main/java/rs/edu/raf/banka/user_service/service/implementation/UserServiceImplementation.java
Labels: bug
